/*
 * This file is generated by jOOQ.
 */
package com.jooq.db;


import com.jooq.db.tables.Databasechangeloglock;
import com.jooq.db.tables.Employees;
import com.jooq.db.tables.Tasks;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;
}
