server:
  port: 8081
spring:
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TestTask
    username: postgres
    password: mosh9990
    hikari:
      connectionTimeout=30000