/*
 * This file is generated by jOOQ.
 */
package com.jooq.db.tables.records;


import com.jooq.db.tables.Employees;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.employees.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employees.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.employees.post</code>.
     */
    public void setPost(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employees.post</code>.
     */
    public String getPost() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.employees.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.employees.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.employees.filial</code>.
     */
    public void setFilial(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.employees.filial</code>.
     */
    public String getFilial() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.employees.chiefid</code>.
     */
    public void setChiefid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.employees.chiefid</code>.
     */
    public Integer getChiefid() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Employees.EMPLOYEES.ID;
    }

    @Override
    public Field<String> field2() {
        return Employees.EMPLOYEES.POST;
    }

    @Override
    public Field<String> field3() {
        return Employees.EMPLOYEES.NAME;
    }

    @Override
    public Field<String> field4() {
        return Employees.EMPLOYEES.FILIAL;
    }

    @Override
    public Field<Integer> field5() {
        return Employees.EMPLOYEES.CHIEFID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPost();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getFilial();
    }

    @Override
    public Integer component5() {
        return getChiefid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPost();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getFilial();
    }

    @Override
    public Integer value5() {
        return getChiefid();
    }

    @Override
    public EmployeesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EmployeesRecord value2(String value) {
        setPost(value);
        return this;
    }

    @Override
    public EmployeesRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public EmployeesRecord value4(String value) {
        setFilial(value);
        return this;
    }

    @Override
    public EmployeesRecord value5(Integer value) {
        setChiefid(value);
        return this;
    }

    @Override
    public EmployeesRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Integer id, String post, String name, String filial, Integer chiefid) {
        super(Employees.EMPLOYEES);

        setId(id);
        setPost(post);
        setName(name);
        setFilial(filial);
        setChiefid(chiefid);
    }
}
