server:
  port: 8081
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TestTask
    user: postgres
    password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TestTask
    username: postgres
    password: admin
    hikari:
      connectionTimeout=30000